### ISSUE TITLE
The user must log in Jira service in the browser first before calling jiji

### ISSUE THREAD

**Issue by rshiue** [rshiue/jiji#5]

**Comment by rshiue** [comment]
Given the user calls jiji before logging in
Then `jiji` will raise the following error:

```
Traceback (most recent call last):
  File "D:\projects\myvv\Scripts\jiji-script.py", line 11, in <module>
    load_entry_point('jiji==0.1.0', 'console_scripts', 'jiji')()
  File "d:\projects\myvv\lib\site-packages\jiji\__main__.py", line 3, in main
    return main()
  File "d:\projects\myvv\lib\site-packages\jiji\core.py", line 28, in main
    build_workbook(query(__default_jql_option_adapter), query)
  File "d:\projects\myvv\lib\site-packages\jiji\client.py", line 40, in __call__
    return self.__collect_issues(adapter_func)
  File "d:\projects\myvv\lib\site-packages\jiji\client.py", line 46, in __collect_issues
    return resp.json()
  File "d:\projects\myvv\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\RobertPC\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\RobertPC\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\RobertPC\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(myvv) D:\projects>
(myvv) D:\projects>

```
